#!/usr/bin/env python3

import sys
sys.path.insert(0, "/app/share/scopebuddygui") # flatpak path

#PySide6, Qt Designer UI files
from PySide6.QtWidgets import QApplication, QMainWindow, QDialog
from PySide6.QtGui import QIntValidator
from ui_mainwindow import Ui_MainWindow  # Import generated UI file
from ui_about import Ui_Dialog_About  # Import generated UI file
from ui_apply_confirmation import Ui_Dialog_Apply
from ui_apply_error import Ui_Dialog_ApplyError
  
import os
from scbgui_functions import * # import the functions from scbgui_functions.py

scbpath = os.path.expanduser('~/.config/scopebuddy/scb.conf')


class MainWindow(QMainWindow,Mixins): 
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow() # imported from ui_mainwindow.py, generated by Qt Designer using mainwindow.ui
        self.ui.setupUi(self)
        self.setWindowTitle("ScopeBuddy GUI")  # Set the window title
        self.ui.variable_displayGamescope.setText(f'Current Gamescope Config: {self.read_gamescope_args()}') #display the current gamescope args

        # Button actions
        self.ui.pushButton_apply.clicked.connect(self.apply_clicked)
        self.ui.pushButton_exit.clicked.connect(self.exit_app)
        self.ui.pushButton_about.clicked.connect(self.open_about_dialog)

        # Input field validation 
        self.ui.lineEdit_oHeight.setValidator(QIntValidator()) # ensures valid inputs.
        self.ui.lineEdit_rHeight.setValidator(QIntValidator()) # input fields are also limited to 
        self.ui.lineEdit_oWidth.setValidator(QIntValidator())  # 4 digits in Qt Designer to ensure sane configs,
        self.ui.lineEdit_rWidth.setValidator(QIntValidator())  # unless a different value is more logical.
        self.ui.lineEdit_fps.setValidator(QIntValidator())
        self.ui.lineEdit_maxScaleFactor.setValidator(QIntValidator())
        self.ui.lineEdit_upscalerSharpness.setValidator(QIntValidator())

        gamescope_path = locate_dependency('gamescope') # check if gamescope is installed
        scopebuddy_path = locate_dependency('scopebuddy')
        if not (gamescope_path and scopebuddy_path):
            self.ui.variable_displayGamescope.setText("Gamescope or ScopeBuddy not found, no changes made will be saved.")
            self.ui.variable_displayGamescope.setStyleSheet("color: red;")

        

        


        self.apply_current_to_ui()

    # ON-CLICK METHODS

    def apply_clicked(self):
        print("Apply button clicked...")
        if not self.ensure_valid_args()[0]:
            dialog = Dialog_ApplyError()
            dialog.exec()
            raise ValueError
        dialog = DialogApply()
        dialog.exec()
        if dialog.answer:
            print('Applying changes...')
            self.apply_global_config()

    def exit_app(self):
        print("Exiting application...")
        sys.exit()

    def open_about_dialog(self):
        print("Opening about dialog...")
        dialog = DialogAbout()
        dialog.exec() #TODO: popup can go behind the main window, while blocking inputs on the main window...

class DialogAbout(QDialog):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Dialog_About()
        self.ui.setupUi(self)
        self.setWindowTitle("About ScopeBuddy GUI")  # Set the window title
        self.ui.pushButton_okay.clicked.connect(self.close)

class Dialog_ApplyError(QDialog):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Dialog_ApplyError()
        self.ui.setupUi(self)
        self.setWindowTitle("Error!")  # Set the window title
        self.ui.pushButton_Ok.clicked.connect(self.close)

class DialogApply(QDialog):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Dialog_Apply()
        self.ui.setupUi(self)
        self.setWindowTitle("Apply Changes?")  # Set the window title
        self.ui.var_currentConfig.setText(MainWindow.read_gamescope_args(window))
        self.ui.var_newConfig.setText(MainWindow.generate_new_config(window))

        #button actions
        self.ui.pushButton_Cancel.clicked.connect(self.close)
        self.ui.pushButton_Apply.clicked.connect(self.apply_changes)
        self.answer = False #changes will not be applied unless explictly confirmed
        
        if not (locate_dependency('gamescope') and locate_dependency('scopebuddy')):
            print("Gamescope or ScopeBuddy not found, disabling file writing.")
            self.ui.pushButton_Apply.setEnabled(False)
            self.ui.label.setText("Gamescope or ScopeBuddy not found, unable to write to config file.")
            self.ui.label.setStyleSheet("color: red;")
            self.ui.label_4.setText('Ensure they are properly installed for this program to work.')
    
    def apply_changes(self):
        self.answer = True #changes have been explicitly confirmed
        self.close()





app = QApplication([]) # pass the arguments to the QApplication constructor
window = MainWindow()
window.show()
app.exec()

